[package]
name = "BFNgameengine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28.1"
env_logger = "0.10.0"
log = "0.4.17"
wgpu = "0.15.1"
queues = "1.1.0"